<a href="https://colab.research.google.com/github/AdelineKwakye/walmart-huricane-project/blob/main/notebooks/scratch/Vi_Nguyen_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
#load pandas library
import pandas as pd
#load in product_catalog using pandas
df=pd.read_csv('/content/product_catalog.csv')
#strip product name
df['product_name']=df['product_name'].str.strip()
#lowercase
df['product_name']=df['product_name'].str.lower()
#remove spaces
df['product_name']=df['product_name'].str.replace(' ','')

# Grouped list of terms and their unified SKUs
mapping_rules = {
    'batteries': 'BAT-AA4',
    'formula': 'BFORM-01',
    'beer': 'BEER-24',
    'monopoly': 'MONOPOLY-01',
    'whitebread': 'BREAD-WH',
    'candle': 'CANDLE-EMRG',
    'playingcards': 'CARDS-01',
    'variety': 'CHIPS-VP',
    'charger': 'CHRG-PORT',
    'diaper': 'DIAPERS-3',
    'firstaid': 'FAID-01',
    'aidkit': 'FAID-01',
    'flashlight': 'FLASH-01',
    'tarp': 'HDTARP-01',
    'papertowel': 'PTOWEL-6',
    'peanut': 'PNUTBTR-16',
    'poptart': 'POPTART-STRAW',
    'strawberrypop': 'POPTART-STRAW',
    'pop-tartsstrawberry': 'POPTART-STRAW',
    'streaming': 'ROKU-STD',
    'roku': 'ROKU-STD',
    'soup': 'CNSOUP-01',
    'toiletpaper': 'TP-12',
    'water': 'WTR-24'
}

# Apply mapping rules
for key, sku in mapping_rules.items():
    df.loc[df['product_name'].str.contains(key), 'sku'] = sku

# Show finalized groups to verify all product names mapped to single SKUs
print(df.groupby('sku')['product_name'].unique())

sku
BAT-AA4                        [batteriesaa4pk, aabatteries4-pack]
BEER-24                                       [lightbeer(24-pack)]
BFORM-01                              [infantformula, babyformula]
BREAD-WH                                              [whitebread]
CANDLE-EMRG                 [candles(emergency), emergencycandles]
CARDS-01                                            [playingcards]
CHIPS-VP                     [varietypack-chips, chipsvarietypack]
CHRG-PORT                  [portablecharger, portablephonecharger]
CNSOUP-01                                [soup-canned, cannedsoup]
DIAPERS-3                          [babydiapers-size3, diaperssz3]
FAID-01                                [first-aidkit, firstaidkit]
FLASH-01                                           [flashlightled]
HDTARP-01                          [heavydutytarp, tarp-heavyduty]
MONOPOLY-01                [monopolyboardgame, boardgame-monopoly]
PNUTBTR-16                                          [peanutbutter]
POPTART-STRAW            [pop-tartsstrawberry, strawberrypop-tart]
PTOWEL-6                                             [papertowels]
ROKU-STD                     [rokustreamingstick, streamingdevice]
TP-12                        [toiletpaper12pk, toiletpaper12-roll]
WTR-24           [bottledwater24pk, bottledwater24-pack, water-...
Name: product_name, dtype: object

In [32]:
# Load the original product catalog
orig_df = pd.read_csv('/content/product_catalog.csv')

# Let's select a few relevant columns to compare
columns_to_show = ['sku', 'product_name', 'category']

print("--- BEFORE MAPPING (Sample) ---")
display(orig_df[columns_to_show].head(15))

print("\n--- AFTER MAPPING (Sample) ---")
display(df[columns_to_show].head(15))

#print before and after # of unique sku
print("\n--- BEFORE MAPPING (Unique SKUs) ---")
print(orig_df['sku'].nunique())
print("\n--- AFTER MAPPING (Unique SKUs) ---")
print(df['sku'].nunique())

--- BEFORE MAPPING (Sample) ---

              sku           product_name             category
0           PT-12   pop-tarts strawberry      Breakfast Foods
1      SKU#459812    Strawberry Pop-Tart            Breakfast
2   POPTART-STRAW   Pop-Tarts Strawberry            Breakfast
3   PT_STRAWBERRY   pop-tarts strawberry            breakfast
4          WTR-24     BOTTLED WATER 24PK   Emergency Supplies
5       WATER24PK  Bottled Water 24-Pack            Emergency
6        WTR_24PK        Water - 24 Pack            Emergency
7        BATT-100       BATTERIES AA 4PK   Emergency Supplies
8         BAT-AA4    AA Batteries 4-Pack   Emergency Supplies
9     BATT_AA_4PK    AA Batteries 4-Pack            Emergency
10       FLASH-01         FLASHLIGHT LED            Emergency
11      LED-FLASH         FLASHLIGHT LED            EMERGENCY
12        BEER-24   Light Beer (24-pack)  Alcoholic Beverages
13       LTBEER24   Light Beer (24-pack)              ALCOHOL
14        BG-MONO    Monopoly Board Game        ENTERTAINMENT

--- AFTER MAPPING (Sample) ---

              sku         product_name             category
0   POPTART-STRAW  pop-tartsstrawberry      Breakfast Foods
1   POPTART-STRAW   strawberrypop-tart            Breakfast
2   POPTART-STRAW  pop-tartsstrawberry            Breakfast
3   POPTART-STRAW  pop-tartsstrawberry            breakfast
4          WTR-24     bottledwater24pk   Emergency Supplies
5          WTR-24  bottledwater24-pack            Emergency
6          WTR-24         water-24pack            Emergency
7         BAT-AA4       batteriesaa4pk   Emergency Supplies
8         BAT-AA4    aabatteries4-pack   Emergency Supplies
9         BAT-AA4    aabatteries4-pack            Emergency
10       FLASH-01        flashlightled            Emergency
11       FLASH-01        flashlightled            EMERGENCY
12        BEER-24   lightbeer(24-pack)  Alcoholic Beverages
13        BEER-24   lightbeer(24-pack)              ALCOHOL
14    MONOPOLY-01    monopolyboardgame        ENTERTAINMENT

--- BEFORE MAPPING (Unique SKUs) ---
45

--- AFTER MAPPING (Unique SKUs) ---
20

In [42]:
#load the walmart transactions data
df_trans=pd.read_csv('/content/walmart_transactions.csv')
df_trans

#strip product name
df_trans['product_name']=df_trans['product_name'].str.strip()
#lowercase
df_trans['product_name']=df_trans['product_name'].str.lower()
#remove spaces
df_trans['product_name']=df_trans['product_name'].str.replace(' ','')

#Apply mapping rules
df_trans['sku']=df_trans['sku'].map(mapping_rules)

for key, sku in mapping_rules.items():
    df_trans.loc[df_trans['product_name'].str.contains(key), 'sku'] = sku

df_trans

,transaction_id,store_id,timestamp,sku,product_name,category,quantity,unit_price
0,TXN012636,FL-710,2024-09-24T09:48:13,PNUTBTR-16,peanutbutter,Grocery,1,3.15
1,TXN000759,fl-412,2024-09-13 20:30:20,CNSOUP-01,cannedsoup,GROCERY,1,2.02
2,TXN003338,FL-105,2024-09-17 10:06:00,TP-12,toiletpaper12-roll,Household Essentials,2,10.47
3,TXN025020,FL-330,2024-09-11 06:29:08,ROKU-STD,rokustreamingstick,ELECTRONICS,1,28.59
4,TXN015797,FL-302,2024-09-26 15:59:42,BEER-24,lightbeer24pk,Alcoholic Beverages,3,18.82
...,...,...,...,...,...,...,...,...
25557,TXN020201,FL-105,2024-09-03T18:28:07,DIAPERS-3,diaperssize3,baby,2,24.32
25558,TXN014835,FL-239,09-26-2024 08:47:08,CARDS-01,playingcards,Games & Entertainment,3,5.00
25559,TXN002434,fl-239,16-Sep-2024 16:39,PTOWEL-6,papertowels6-roll,household,2,7.78
25560,TXN014739,FL-710,2024-09-25 17:08:35,CHRG-PORT,portablecharger,electronics,1,24.18
25561,TXN010981,FL-105,24-Sep-2024 06:32,DIAPERS-3,diaperssize3,baby,2,24.90